### PR TITLE
Add options, update validate request attribute, and add dependency injection extensions

### PR DESCRIPTION
**Pull request by Swimburger**
This PR currently does a couple of things:

1. It adds `TwilioOptions` which are used to configure the `TwilioRestClient` and `ValidateRequestAttribute`. This can be configured using `AddTwilio` or `AddTwilioOptions`.
2. It updates `ValidateRequestAttribute` to fetch configuration via `TwilioOptions`, while still allowing developers to configure the attribute via its properties. 
3. It adds `ITwilioRestClient` and `TwilioRestClient` to the dependency injection (DI) container using the `AddTwilio`, or `AddTwilioOptions` + `AddTwilioClient` methods. With this change, you can also provide your own `HttpClient` so developers can use the ASP.NET Core `HttpClientFactory` patterns.

**Let's take a closer look at 1.**
Here's how to register the options using DI:
```csharp
using Twilio.AspNet.Core;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddTwilio();
```

This will load the configuration from the `Twilio` section. This configuration looks like this in JSON format:
```json
{
  "Twilio": {
    "AuthToken": "[YOUR_AUTH_TOKEN]",
    "Client": {
      "AccountSid": "[YOUR_ACCOUNT_SID]",
      "AuthToken": "[YOUR_AUTH_TOKEN]",
      "ApiKeySid": "[YOUR_API_KEY_SID]",
      "ApiKeySecret": "[YOUR_API_KEY_SECRET]",
      "CredentialType": "[Unspecified|AuthToken|ApiKey]",
      "Region": null,
      "Edge": null,
      "LogLevel": null
    },
    "RequestValidation": {
      "AuthToken": "[YOUR_ACCOUNT_SID]",
      "AllowLocal": true,
      "UrlOverride": "https://??????.ngrok.io/sms"
    }
  }
}
```
**Danger: Don't put your AuthToken or secret in source control, including your _appsettings.json_ files. Instead, use user-secrets or environment variables.**

If `Twilio:Client:AuthToken` isn't configured, it'll fallback to `Twilio:AuthToken`. Same applies to `Twilio:RequestValidation:AuthToken`. This way you can configure the auth token in `Twilio:AuthToken` once without having to configure it in `Twilio:Client:AuthToken` or `Twilio:RequestValidation:AuthToken`.
However, you can override it if your client needs a different Auth Token than your request validator.

`AddTwilio` is a shortcut for `.AddTwilioOptions().AddTwilioClient()`.

If you don't want to use the `Twilio` section, you can configure the options as follows:
```csharp
using Twilio.AspNet.Core;

var builder = WebApplication.CreateBuilder(args);

builder.Services
  .AddTwilioOptions((serviceProvider, options) =>
  {
    options.AuthToken = "";

    options.Client.AccountSid = "";
    options.Client.AuthToken = "";
    options.Client.ApiKeySid = "";
    options.Client.ApiKeySecret = "";
    options.Client.Edge = "";
    options.Client.Region = "";
    options.Client.CredentialType = CredentialType.Unspecified;

    options.RequestValidation.AuthToken = "";
    options.RequestValidation.AllowLocal = true;
    options.RequestValidation.UrlOverride = "";
  });
```

In this example, all the options are hardcoded, but you can request any service from the `serviceProvider` and configure your options programatically.

**Let's take a closer look at 2.**
Previously, you could use the `ValidateRequestAttribute` and pass in values through the constructor and properties.
Now you can still use the properties, but not the constructor.

**Note: I think we should remove the setters from the  `ValidateRequestAttribute` to force the developer to use configuration instead of hardcoding secrets and environment specific configuration.**

To use the `TwilioOptions` to configure `ValidateRequestAttribute`, use the parameterless constructor and don't specify properties during object initialization:

Before:
```csharp
[ValidateRequest("your auth token here", urlOverride: "https://??????.ngrok.io/sms")]
```

After:
```csharp
[ValidateRequest]
```

You can still hardcode via the attribute properties which will override the `TwilioOptions`:
```
[ValidateRequest(AllowLocal = true)]
```

**Let's take a closer look at 3.**
The `ITwilioRestClient` and `TwilioRestClient` can be added as a transient service to ASP.NET Core's DI container using the `AddTwilio` or `AddTwilioOptions().AddTwilioClient()` methods.
As a result, you can request `ITwilioRestClient` and `TwilioRestClient` via DI where an `IServiceScope` is used, meaning anywhere where DI is usually supported such as controllers, pages, endpoints, background workers, etc.

Here's an example of `ITwilioRestClient` being injected into a controller action, using the `FromServices` attribute:
```csharp
public class SmsController : Controller
{
    public TwiMLResult Index([FromServices] ITwilioRestClient twilioClient)
    {
      // do something
    }
}
```
You could also use constructor injection or any other techniques to request the Twilio client.

This is helpful, but in addition to the empty `AddTwilio` or `AddTwilioClient` method signature,
you can also provide a callback to the `AddTwilioClient` method which allows you to provide an instance of `HttpClient`.
This way you could use the `HttpClientFactory` to manage the lifetime of your `HttpClient` which helps prevent socket exhaustion and DNS staleness among many benefits and additional capabilities.
(See [issues with the original HttpClient](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net)).

Here's an example of using the `HttpClientFactory` integration in ASP.NET Core:
```csharp
using Twilio.AspNet.Core;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpClient();

builder.Services
    .AddTwilioOptions()
    .AddTwilioClient(provider => provider.GetRequiredService<IHttpClientFactory>().CreateClient());
```

---

I'm not entirely convinced of this PR yet, so I'm leaving it as a draft for now.
Specifically, I think the `AddTwilioOptions` should be refactored so that the options are configured in `AddTwilioClient` and a new `AddTwilioRequestValidator` method.
The majority of the code has been unit tested, however inline documentation needs to be written.

Looking for feedback!! 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by Swimburger** [comment]
This PR would avoid having to hardcode the sensitive Auth Token into the `ValidateRequestAttribute` which was the initial goal of this development effort to fix #49.

This doesn't include a solution for the .NET Framework version.

**Comment by Swimburger** [comment]
@dprothero 

1: I originally had a single `AddTwilio`. There'd be a callback to configure the options and a callback to provide the `HttpClient`. I didn't like how it had the second callback for the `HttpClient` as it wasn't clear what the `HttpClient` was for.

I felt that the `AddTwilioClient` with the callback to provide an `HttpClient` made it much clearer that the `HttpClient` would be used for the Twilio client.

2: Yes, I think it's a good idea to bake this in as a default. I wasn't daring enough to change the default implementation of the `TwilioRestClient`, but I don't see why not.

I'm actually leaning towards dropping `AddTwilio` and have developers use `AddTwilioClient` and a to be added `AddTwilioRequestValidator`.
It's more verbose and explicit which more clearly communicates what it's doing and allows the developer to choose what features they want to add.

**Comment by dprothero** [comment]
@Swimburger that sounds good to me.

**Comment by Swimburger** [comment]
I refactored out the `AddTwilio` method and `AddTwilioOptions`. Here's an updated sample:

```csharp
using Twilio.AspNet.Core;

var builder = WebApplication.CreateBuilder(args);

builder.Services
  .AddTwilioClient((serviceProvider, options) =>
  {
    options.AccountSid = "";
    options.AuthToken = "";
    options.ApiKeySid = "";
    options.ApiKeySecret = "";
    options.Edge = "";
    options.Region = "";
    options.CredentialType = CredentialType.Unspecified;
  })
  .AddTwilioRequestValidation((serviceProvider, options) =>
  {
    options.AuthToken = "";
    options.AllowLocal = true;
    options.UrlOverride = "";
  });
```

When calling `AddTwilioClient` without a callback to provide an `HttpClient`, a named HTTP client will be added which will be used with the HTTP client factory to provide an `HttpClient` to the Twilio client.

The `ValidateRequest` attribute does not accept parameters in its constructor nor has public properties to configure the attribute. All configuration happens through the `AddTwilioRequestValidation` method.

**Comment by ericsampson** [comment]
I have some thoughts about this PR regarding changes to follow Microsoft's suggested patterns, but I'm not sure that I'm going to have time to write them down this week or even next unfortunately :(

**Comment by Swimburger** [comment]
@dprothero after consulting with some folks, I decided to add the Twilio client as a scoped service.
I would like to merge the changes. Can you review this PR for me?

**Review by dprothero — APPROVED** [review]
@Swimburger It looks good! I'm wondering about the version number, however. Since we're making a breaking change to the `ValidateRequestAttribute`, we should consider bumping the major version number. This does mean that we would no longer be in sync with the Twilio helper library versioning, but maybe that's OK.

**Comment by Swimburger** [comment]
@dprothero agreed!

We need to bump a major version. 
Maybe we should stop following the version of the Twilio library since they're separate libraries?

I did like it because I would know the version of Twilio lib it would come with.

**Comment by dprothero** [comment]
Yeah, I think we have to stop following the helper library version.

**Pull request merged**
