### PR TITLE
Add types for Minimal API

### PR DESCRIPTION
**Pull request by Swimburger**
_At this point, the PR is meant for discussion, not to be merged in._

ASP.NET Core 6 introduced a new way to build web applications using Minimal API.
This doesn't use controllers or action results, but uses the new `IResult` type.
It is suggested to add extension methods to `IResultExtensions` so it can be invoked using `Results.Extensions.YourExtension`.
Here's the guidance I found: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#customizing-results

To get this to work, I had to make a couple of decisions which should be up for discussion:
- The types only seemed to be recognized when targeting `net6.0`. This is probably not acceptable to maintain support for older versions of .NET.
- The types are in a separate namespace `Twilio.AspNet.Core.MinimalApi` to prevent name collisions.
- I don't see much value in adding the extension to `IResultExtensions`, it'll make it so the extension method is available at `Results.Extensions.TwiML`, but we could just create our own static type `TwilioResults.TwiML` or something similar.

This is how the new code would be used:
```csharp
app.MapGet("/voice", () =>
{
    var response = new VoiceResponse();
    response.Say("Hello World!");
    return Results.Extensions.TwiML(response);
});
app.MapGet("/message", () =>
{
    var response = new MessagingResponse();
    response.Message("Hello World!");
    return Results.Extensions.TwiML(response);
});
```

What do y'all think?

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by Swimburger** [comment]
Couple of updates:
- I learned how to use C# preprocessor conditionals, so we can include these new features while still supporting older versions of .NET.
- For multi-targeting to work with .NET 6, the build script needed to be updated to use the dotnet CLI more
- We'll keep using `Results.Extensions.TwiML` as it is the recommended way 
- Version has been bumped to 5.71.0
- @dprothero is helping me onboard on this project

**Comment by Swimburger** [comment]
@dprothero what are the next steps to get this towards a mergable state?

**Comment by dprothero** [comment]
@Swimburger I think it's there!

**Comment by Swimburger** [comment]
@dprothero this is ready for review, would you like to review it or should I ask someone else?

**Review by dprothero — APPROVED** [review]
Nice work! Lots of yak shaving to be done, but it looks good.

**Pull request merged**
